Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2018-12, with the labels that each got.

#5 Add csi prefix to image name
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6 Cherry-pick #5 to release-1.0: Add csi prefix to image name
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4 Fix docker image version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9 Add msau42 to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10 Make registration path mandatory, remove kubeconfig parameter
  cmd/node-driver-registrar/main.go
  cmd/node-driver-registrar/node_register.go
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#14 Cherry pick #10 to release-1.0: Make registration path mandatory, remove kubeconfig parameter
  cmd/node-driver-registrar/main.go
  cmd/node-driver-registrar/node_register.go
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#15 Remove retrieval of node name
  cmd/node-driver-registrar/main.go
  cmd/node-driver-registrar/node_register.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#13 Update documentation and argument descriptions
  README.md
  cmd/node-driver-registrar/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#17 Cherry pick #13 to release-1.0: Update documentation and argument descriptions
  README.md
  cmd/node-driver-registrar/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#18 fix release link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#19 Cherry pick #18 to release-1.0: fix release link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
