Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2019-04, with the labels that each got.

#38 Add Changelog for 1.1.0
  CHANGELOG-1.1.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#37 Prow testing
  .prow.sh
  release-tools/.prow.sh
  release-tools/README.md
  release-tools/build.make
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/util.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#40 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#39 update to Go 1.12.4
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
