Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2019-02, with the labels that each got.

#25 Update compatibility matrix to only reflect branch head
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#26 add note about readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#27 sync master README to release-1.0
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#24 Migrate to k8s.io/klog from glog.
  Gopkg.lock
  Gopkg.toml
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
  pkg/connection/connection.go
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#28 update owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#30 Updating README with required mounts
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 node driver registrar should use CSI connection lib
  Gopkg.lock
  Gopkg.toml
  cmd/csi-node-driver-registrar/main.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/release-tools/LICENSE
Labels: approved, cncf-cla: yes, lgtm, size/L

#31 Remove unused code
  pkg/connection/connection.go
  pkg/connection/connection_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#33 Use GetDriverName from csi-lib-utils
  Gopkg.lock
  Gopkg.toml
  cmd/csi-node-driver-registrar/main.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/github.com/kubernetes-csi/csi-test/LICENSE
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.mock.go
  vendor/github.com/kubernetes-csi/csi-test/driver/mock.go
  vendor/github.com/kubernetes-csi/csi-test/mock/AUTHORS
  vendor/github.com/kubernetes-csi/csi-test/utils/grpcutil.go
  vendor/github.com/kubernetes-csi/csi-test/utils/safegoroutinetester.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/serverreflection.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
