Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2019-09, with the labels that each got.

#42 Correct repository name of driver-registrar
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#47 Build Node Driver Registrar for Windows nodes
  Dockerfile.Windows
  cmd/csi-node-driver-registrar/node_register.go
  cmd/csi-node-driver-registrar/util_linux.go
  cmd/csi-node-driver-registrar/util_windows.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#50 Prow update master
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#49 add 1.2 changelog
  CHANGELOG-1.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
