Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2019-01, with the labels that each got.

#20 Add source code comment and fix readme formatting issues.
  README.md
  pkg/connection/connection.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#22 Small markdown linter correction.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#23 release tools
  .gitignore
  .travis.yml
  Dockerfile
  Makefile
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/build.make
  release-tools/code-of-conduct.md
  release-tools/travis.yml
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL
