Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2020-05, with the labels that each got.

#82 Tagging of multiarch images on gcr
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#84 multiarch image pushing
  .cloudbuild.sh
  Dockerfile
  Dockerfile.multiarch
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#85 cloud build: fix shell syntax
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#86 master: update release-tools
  .cloudbuild.sh
  cloudbuild.yaml
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
