Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2020-04, with the labels that each got.

#71 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#72 Fixing cloudbuild.yml for multiarch Docker Image support
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/XS

#73 Add links to version in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#74 Update to newer gcb-docker-gcloud image with docker 19.03.5
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#75 update to latest gcr.io/k8s-testimages/gcb-docker-gcloud image
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#76 Set $HOME to /root for buildx to be picked up
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#77 Make base image and tag configrable in Dockerfile.Windows
  Dockerfile.Windows
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#78 build both platforms and generate manifest as well
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#80 Add build step for Windows container image
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#79 Fix to exec format error on non-intel arch
  Dockerfile.multiarch
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/XS
