Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2020-08, with the labels that each got.

#95 Add flag to configure the registration socket path
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#98 Prepare release v2.0
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-2.0.md
  README.md
  go.mod
  go.sum
  vendor/k8s.io/client-go/util/testing/tmpdir.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#102 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#103 Update registry for sample container in README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#99 HTTP server for liveness probe, check registration socket exists
  README.md
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
  pkg/util/util_linux.go
  pkg/util/util_test.go
  pkg/util/util_windows.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#105 Update 2.0 changelog
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#101 Make nanoserver tag configurable
  Dockerfile.Windows
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#106 Bump kube version to 1.19.0 and CSI spec to 1.3.0
  README.md
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#107 Update 2.0 changelog
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
