Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2020-12, with the labels that each got.

#125 Introduce http-endpoint flag
  README.md
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#124 add --timeout for gRPC calls
  README.md
  cmd/csi-node-driver-registrar/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XS

#130 Add release-note for v2.1.0
  CHANGELOG/CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#131 move release note to deprecations
  CHANGELOG/CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
