Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2020-03, with the labels that each got.

#68 Multiarch Docker Image support using GCB
  Dockerfile.multiarch
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#70 Add 1.3 changelog
  CHANGELOG-1.3.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#69 Update main.go
  cmd/csi-node-driver-registrar/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
