Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2021-08, with the labels that each got.

#152 Provide different running modes for node-driver-registrar, add a run mode to detect if the kubelet plugin registration failed
  README.md
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
  pkg/util/util_linux.go
  pkg/util/util_test.go
  pkg/util/util_windows.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#159 Update k8s dependencies to v1.22.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, sig/storage, size/M

#160 Use csi-lib-utils v0.10.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: kind/feature, size/M, cncf-cla: yes, approved, lgtm, release-note

#162 Clean up .travis.yml
  .travis.yml
  README.md
Labels: kind/cleanup, cncf-cla: yes, ok-to-test, approved, lgtm, size/XS, release-note-none

#161 Add platform linux/arm
  release-tools/README.md
  release-tools/SECURITY_CONTACTS
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: kind/feature, size/M, cncf-cla: yes, ok-to-test, approved, lgtm, release-note
