Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2022-12, with the labels that each got.

#245 Do not print success log when error appears
  cmd/csi-node-driver-registrar/main.go
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XS, release-note-none

#258 Upgrade csi-lib-utils to v0.12.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: kind/cleanup, cncf-cla: yes, approved, lgtm, release-note-none, size/L

#260 Add CHANGELOG-2.7md for k8s 1.26.0 release
  CHANGELOG/CHANGELOG-2.7.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, release-note-none, size/L
