Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2022-04, with the labels that each got.

#191 master: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note-none

#190 Correct the handler used in serving http requests
  cmd/csi-node-driver-registrar/node_register.go
Labels: kind/bug, cncf-cla: yes, ok-to-test, lgtm, release-note, size/XS

#192 Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/L

#193 Automated cherry pick of #190: Correct the handler used in serving http requests
  cmd/csi-node-driver-registrar/node_register.go
Labels: cncf-cla: yes, approved, lgtm, release-note, size/XS
