Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2022-10, with the labels that each got.

#225 Update go version in go.mod
  go.mod
  go.sum
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/emicklei/go-restful/v3/go.mod
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-openapi/jsonpointer/go.mod
  vendor/github.com/go-openapi/jsonpointer/go.sum
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/modules.txt
Labels: kind/cleanup, cncf-cla: yes, approved, lgtm, release-note-none, size/L

#220 Fixes link of contributor cheat sheet
  CONTRIBUTING.md
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XS, release-note-none

#227 Bump all k8s dependencies to v0.25.2
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: size/XL, kind/cleanup, cncf-cla: yes, approved, lgtm, release-note-none

#231 Changelog for v2.6.0
  CHANGELOG/CHANGELOG-2.6.md
Labels: kind/cleanup, cncf-cla: yes, approved, lgtm, release-note-none, size/L

#233 master: update release-tools
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/prow.sh
Labels: size/M, cncf-cla: yes, approved, lgtm, release-note-none
