Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2023-11, with the labels that each got.

#352 Bump google.golang.org/grpc to fix CVE-2023-44487
  go.mod
  go.sum
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: kind/bug, size/XL, cncf-cla: yes, ok-to-test, approved, lgtm, release-note

#353 Add changelog for v2.9.1
  CHANGELOG/CHANGELOG-2.9.md
Labels: size/M, cncf-cla: yes, kind/documentation, ok-to-test, approved, lgtm, release-note-none

#358 Add changelog for v2.9.2
  CHANGELOG/CHANGELOG-2.9.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, release-note-none, size/S
