Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2023-09, with the labels that each got.

#316 Deprecate kubelet-registration-probe
  README.md
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
  pkg/util/util_test.go
  pkg/util/util_unix.go
  pkg/util/util_windows.go
Labels: kind/cleanup, cncf-cla: yes, approved, lgtm, release-note, size/L

#331 csi-release-tools update
  release-tools/SIDECAR_RELEASE_PROCESS.md
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/S

#332 Add changelog for v2.9
  CHANGELOG/CHANGELOG-2.9.md
  README.md
Labels: cncf-cla: yes, kind/documentation, approved, lgtm, release-note-none, size/L

#336 Enable dependabot raising PR by groups
  .github/dependabot.yaml
Labels: kind/cleanup, cncf-cla: yes, approved, lgtm, release-note-none, size/S
