Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2023-12, with the labels that each got.

#364 Update release tools to fix broken image build pipeline
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-modules-update.sh
  release-tools/prow.sh
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/L

#366 Update dependency go modules for k8s v1.29.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, cncf-cla: yes, approved, lgtm, release-note

#368 Update csi-lib-utils to v0.17.0
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: size/XL, cncf-cla: yes, approved, lgtm, release-note-none

#370 [release-2.9] Update go modules
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/S

#372 Changelog for v2.9.3
  CHANGELOG/CHANGELOG-2.9.md
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/S
