Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2024-05, with the labels that each got.

#406 Bump to Kubernetes 1.30
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
  go.mod
  go.sum
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/generate-patch-release-notes.sh
  release-tools/go-modules-targeted-update.sh
  release-tools/prow.sh
  release-tools/verify-logcheck.sh
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/filedesc/desc_list_gen.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/k8s.io/apimachinery/pkg/util/sets/doc.go
  vendor/k8s.io/apimachinery/pkg/util/sets/ordered.go
  vendor/k8s.io/apimachinery/pkg/util/sets/set.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, size/XXL, approved, lgtm, release-note

#410 Support contextual logging
  Makefile
  cmd/csi-node-driver-registrar/main.go
  cmd/csi-node-driver-registrar/node_register.go
  pkg/util/util_test.go
  vendor/k8s.io/klog/v2/ktesting/init/init.go
  vendor/k8s.io/klog/v2/ktesting/options.go
  vendor/k8s.io/klog/v2/ktesting/setup.go
  vendor/k8s.io/klog/v2/ktesting/testinglogger.go
  vendor/modules.txt
Labels: kind/feature, size/XL, kind/cleanup, cncf-cla: yes, approved, lgtm, release-note, priority/important-longterm, wg/structured-logging

#413 Add changelog for v2.11
  CHANGELOG/CHANGELOG-2.11.md
Labels: size/M, cncf-cla: yes, kind/documentation, approved, lgtm, release-note-none
