Repository kubernetes-csi/node-driver-registrar, pull requests merged in 2025-05, with the labels that each got.

#506 Upgrade csi tools
  release-tools/prow.sh
Labels: kind/cleanup, cncf-cla: yes, ok-to-test, approved, lgtm, release-note-none, size/S

#501 test: add trivy github action
  .github/workflows/trivy.yaml
Labels: size/M, kind/cleanup, cncf-cla: yes, approved, lgtm, release-note-none

#495 Add `-autopmaxprocs` flag for configuring `GOMAXPROCS`
  cmd/csi-node-driver-registrar/main.go
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/standardflags/automaxprocs.go
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, size/XXL, approved, lgtm, release-note
